"""avg_speed is 0 default

Revision ID: 9ef36ca8521
Revises: fe637192cea
Create Date: 2015-11-11 17:48:01.956610

"""

# revision identifiers, used by Alembic.
revision = '9ef36ca8521'
down_revision = 'fe637192cea'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
